version: 0.2

env:
  variable:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI
      - npm install -g @angular/cli

  pre_build:
    commands:
      - echo Installing project dependencies
      - npm install

  build:
    commands:
      - echo Building the Angular project
      - ng build

  post_build:
    commands:
      - echo Deploying to S3
      - aws s3 sync dist/your-app-name s3://your-bucket-name/

cache:
  paths:
    - "node_modules/**/*"

artifact:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
